In [2]:
import numpy as np

In [12]:
veri = np.arange(1,21,2).reshape(2,-1)
veri2 = np.array([[1,2,3],[4,5,6]])
veri

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [13]:
veri2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
veri*2

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38]])

In [7]:
veri

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [8]:
veri.argmax()

9

In [9]:
veri.argmin()

0

In [14]:
veri2.argmax()

5

In [15]:
veri2.argmin()

0

In [23]:
veri[0][1:3]

array([3, 5])

In [24]:
veri2[[0,1],[2,1]]

array([3, 5])

In [30]:
veribirleşik = np.concatenate([veri,veri2],axis = 1)
veribirleşik

array([[ 1,  3,  5,  7,  9,  1,  2,  3],
       [11, 13, 15, 17, 19,  4,  5,  6]])

In [31]:
veri.mean()

10.0

In [32]:
veri.std()

5.744562646538029

In [42]:
veri3 = np.random.randint(3,25,10)
veri3

array([ 3, 18, 18, 21, 21, 15, 16, 20,  6, 24])

In [43]:
np.sort(veri3)

array([ 3,  6, 15, 16, 18, 18, 20, 21, 21, 24])

In [46]:
veri3.sort()

In [47]:
veri3

array([ 3,  6, 15, 16, 18, 18, 20, 21, 21, 24])

In [50]:
np.hsplit(veri,[2])

[array([[ 1,  3],
        [11, 13]]), array([[ 5,  7,  9],
        [15, 17, 19]])]

In [51]:
np.vsplit(veri,[1])

[array([[1, 3, 5, 7, 9]]), array([[11, 13, 15, 17, 19]])]

In [54]:
np.linspace(2,58,5)

array([ 2., 16., 30., 44., 58.])