RASTGELE SAYI ÜRETME

In [2]:
import numpy as np

In [4]:
np.random.rand(10)

array([0.22107217, 0.39459662, 0.34683148, 0.07493918, 0.288345  ,
       0.66817279, 0.69714404, 0.79559175, 0.75921938, 0.07938739])

In [5]:
np.random.randn(3)

array([-0.00894098,  0.70126894,  2.28954428])

In [6]:
np.random.normal(2,4,(3,5))

array([[ 6.05703198,  1.08028003, -5.42850873, -2.64026248,  0.43482872],
       [ 5.47307459,  0.72109067,  3.70078654,  0.68179097, -3.66385129],
       [-0.69520937,  2.42349125,  2.08867403, -3.13993657,  3.31331442]])

In [10]:
np.random.randint(1,150,(15,20))

array([[130, 117,  96,  66,  80, 146, 144, 125, 132,  20, 122,  28,  44,
         33,  90,  10,  17, 108, 134, 119],
       [ 33,   5,  68, 149,  81, 136,  73, 136,  56,   2,  68,  11,  79,
         59,  93, 135,  91, 141,  67,  56],
       [ 90, 125,   3, 122,  80,  54,  63, 127, 113,  85,  69,   9, 104,
        110,  56,  24,  55,  98, 116,  25],
       [  3,  73,  82,  56,  23, 100,  63,  19, 138, 107, 137, 112, 139,
         34,  78,  38, 134, 122, 110,  19],
       [ 92, 130,  59,  89, 142, 114,  49,  22,  31,  47,  63,  57, 113,
        114,   6,   8,  66,  47,  85,  27],
       [ 98, 128,  67,  21, 107,  39,   4, 139,  34,  99,  61, 117, 102,
         23, 118,  43, 116,  99, 149, 146],
       [128,  63,  37, 121, 120,  78, 135, 140, 123, 137,   3,  31, 123,
        107,  45,  47, 100, 106, 148,  28],
       [133, 104,  69,  45,   3, 127,  81, 117, 142,   1, 146,  29,  23,
         43,  21,  66,  93,  92, 118, 142],
       [ 40,  12, 101, 147,  30,  91,  34, 138,  10,  35,   7,  

In [14]:
datalar = np.arange(0,40)

In [15]:
datalar = datalar.reshape(5,-1)

In [16]:
datalar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [17]:
datalar.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

İSTATİKTİKSEL İŞLEMLER

In [31]:
import numpy as np
x = np.array([[0,1,2,3],[4,5,6,7],[-1,-2,-3,-4]])
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [-1, -2, -3, -4]])

In [32]:
np.subtract(x,1)#her elemandan bir çıkarır

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [-2, -3, -4, -5]])

In [33]:
np.add(x,3)#her elemana 3 ekler

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 2,  1,  0, -1]])

In [34]:
np.multiply(x,6)#her elemanı 6 ile çarpar

array([[  0,   6,  12,  18],
       [ 24,  30,  36,  42],
       [ -6, -12, -18, -24]])

In [35]:
np.divide(x,3)#her değeri 3'e böler

array([[ 0.        ,  0.33333333,  0.66666667,  1.        ],
       [ 1.33333333,  1.66666667,  2.        ,  2.33333333],
       [-0.33333333, -0.66666667, -1.        , -1.33333333]])

In [36]:
np.power(x,3)#her değerin 3'üncü kuvvetini alır

array([[  0,   1,   8,  27],
       [ 64, 125, 216, 343],
       [ -1,  -8, -27, -64]], dtype=int32)

In [37]:
np.mod(x,2)#her değerin 2 ile bölümünden kalanı bulur

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 0, 1, 0]], dtype=int32)

In [38]:
np.absolute(x)#her elemanın mutlak değerini alır

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

In [42]:
np.std(x,axis = 0)#her sütünun standart sapmasını alır.

array([2.1602469 , 2.86744176, 3.68178701, 4.54606057])

In [40]:
#googleda bir fonksiyonla ilgili arama yaparken sonuna "cheat sheet" eklersen derli olarak bütün fonksiyonları bulabilirsin

Matrislerde Dört İşlem

In [44]:
np.sqrt(np.array([4,9,16]))#karekök alır

array([2., 3., 4.])

In [45]:
np.log(x)#logaritma alır

C:\Users\isaad\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
C:\Users\isaad\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [       nan,        nan,        nan,        nan]])

In [46]:
x.sum()

18

In [47]:
x.mean()

1.5

In [48]:
x.mean(0)

array([1.        , 1.33333333, 1.66666667, 2.        ])

Arraylerde Sıralama

In [49]:
y = np.array([1,22,3,45,768,9,8,568])

In [50]:
np.sort(y)#ana veriyi değiştirmez

array([  1,   3,   8,   9,  22,  45, 568, 768])

In [51]:
y

array([  1,  22,   3,  45, 768,   9,   8, 568])

In [52]:
y.sort()#ana veriyi değiştirir

In [53]:
y

array([  1,   3,   8,   9,  22,  45, 568, 768])

In [55]:
z = np.random.normal(20,5,(3,3))
z

array([[16.41972281, 22.1793117 , 22.7897651 ],
       [14.79399915, 12.51526479, 15.19880582],
       [17.63986051, 15.85459085, 25.86880083]])

In [56]:
np.sort(z,axis = 0)#sütunları sıralar

array([[14.79399915, 12.51526479, 15.19880582],
       [16.41972281, 15.85459085, 22.7897651 ],
       [17.63986051, 22.1793117 , 25.86880083]])

In [57]:
np.sort(z,axis = 1)#satırları sıralar

array([[16.41972281, 22.1793117 , 22.7897651 ],
       [12.51526479, 14.79399915, 15.19880582],
       [15.85459085, 17.63986051, 25.86880083]])

In [59]:
z.ndim

2

In [70]:
z.argmax()#en büyük değerin indexini döndürür

8

In [71]:
z.argmin()#en küçük değerin indexini döndürür

4

Zeros,ones,linspace

In [72]:
zeros = np.zeros((5,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
ones = np.ones((7,15))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [80]:
verim = np.linspace(0,55,6)#verinlen sayılar arasını 6 sayıya böler.
#Yani araları eşit olan 0'dan 55'e kadar sayı oluşturur.
verim

array([ 0., 11., 22., 33., 44., 55.])

In [81]:
np.eye(5)#birim matris oluşturur.
#Birim Matris:köşegeninde 1 olan diğer değerleri sıfır olan kare matris.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Split

In [96]:
array = np.array([1,2,3,4,5,6,7,8])
a,b,c = np.split(array,[3,5])#3'e kadar olan değerleri a arrayine,3'ten 6'ya kadar olanları b arrayine kalanları da c arrayine atar.
a

array([1, 2, 3])

In [98]:
ar = np.arange(1,11).reshape(2,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
ust,alt = np.vsplit(ar,[1])
ust

array([[1, 2, 3, 4, 5]])

In [100]:
sag,sol = np.hsplit(ar,[3])
sol

array([[ 4,  5],
       [ 9, 10]])

ARRAY BİRLEŞTİRME

In [105]:
ar = np.array([1,2,3])
ar2 = np.array([4,5,6])
np.concatenate([ar,ar2])

array([1, 2, 3, 4, 5, 6])

In [116]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr,arr2],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

ARRAYLERDE VERİYE ULAŞMA

In [118]:
ar[ar<2]

array([1])

In [122]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [121]:
a[[1,2,5]]#fancy index

array([ 3,  6, 15])

In [124]:
ar = a.reshape(2,5)
ar

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [165]:
ar[[0,1],[2,3]]#0.satırın 2.sütunundaki değeri ve 1.satırın 3.sütunundaki değeri alır.2.arrayi vermeyerek sadece satırları alabiliriz

array([ 6, 24])